# ARG ELK_VERSION

# https://github.com/elastic/elasticsearch-docker
FROM amazon/opendistro-for-elasticsearch:0.8.0

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
COPY config/elasticsearch.yml /usr/share/elasticsearch/config/elasticsearch.yml